### ISSUE TITLE
error list for unsuccessful jobs

### ISSUE THREAD

**Issue by henry-hz** [mbuhot/ecto_job#4]
Dear @mbuhot , I am thinking about on how to create a PR that deals with job errors, adding an error list in the job data-structure, so every non successful trial will add an error message to the job queue. It will help to have a good vision on what is happening behind the scenes of every job attempt. 

Please, could you send me some small guidelines on how to implement it
regards
Henry

**Comment by mbuhot** [comment]
Good suggestion @henry-hz. 👍 

You'll need to add a new column to the jobs table schema, eg `errors` with data type `:jsonb` or perhaps `{:array, :string}`.

Since the migrations code is in the library, we might need to rename [CreateJobsTable](https://github.com/mbuhot/ecto_job/blob/master/lib/ecto_job/migrations.ex#L36)  to `CreateJobsTable.V1` and then introduce a `CreateJobsTable.V2` for creating new jobs tables and `MigrateJobsTable.V2` for migrating from V1 to V2 schema.

Then you should be able to `rescue` errors raised in [Worker.start_link](https://github.com/mbuhot/ecto_job/blob/master/lib/ecto_job/worker.ex#L25) function, and add the error to the job error list.

Since the job record may have been modified by another worker, I'd run the update query directly against the repo, something like:

```elixir
defmodule EctoJob.JobQueue do
  ... existing code ...

  def record_error(repo, %job{id: id}, error_message) do
    repo.update_all(
      Query.from(j in job, where: j.id == ^id),
      push: [errors: error_message] # not sure if `push` works with jsonb?
    )
  end
end
```

We should also log errors similar to the [log_duration](https://github.com/mbuhot/ecto_job/blob/master/lib/ecto_job/worker.ex#L35) function.

Hope that helps.

**Comment by henry-hz** [comment]
helps! thanks @mbuhot

**Comment by mbuhot** [comment]
Closing this one as it's been inactive for a while.
